// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUNtJJk22kVDZUBCdFS0nOBucFY_IntkM',
    appId: '1:377996365912:web:cfca2dd373e8974854ba2d',
    messagingSenderId: '377996365912',
    projectId: 'whatsapp--clone-d9d46',
    authDomain: 'whatsapp--clone-d9d46.firebaseapp.com',
    storageBucket: 'whatsapp--clone-d9d46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JyJjRO9NvNN5DB7De0rRhKp9AH_ItAA',
    appId: '1:377996365912:android:d676e03bf72fd2b454ba2d',
    messagingSenderId: '377996365912',
    projectId: 'whatsapp--clone-d9d46',
    storageBucket: 'whatsapp--clone-d9d46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBj6PrmXHQunjix1Hv6UtWGXFe78GijvA',
    appId: '1:377996365912:ios:ae61c83bd1b071fa54ba2d',
    messagingSenderId: '377996365912',
    projectId: 'whatsapp--clone-d9d46',
    storageBucket: 'whatsapp--clone-d9d46.appspot.com',
    iosClientId: '377996365912-rdg70pt9an7eu6tjh5a4u1abf6aoj00s.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBj6PrmXHQunjix1Hv6UtWGXFe78GijvA',
    appId: '1:377996365912:ios:1906c42268f4917254ba2d',
    messagingSenderId: '377996365912',
    projectId: 'whatsapp--clone-d9d46',
    storageBucket: 'whatsapp--clone-d9d46.appspot.com',
    iosClientId: '377996365912-dsgrc4ibsqvaopl2tirec5c9pe1n1e37.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
